apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.example.martin-helmich.de
spec:
  group: example.martin-helmich.de
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
  scope: Namespaced
  names:
    plural: projects
    singular: project
    kind: Project
    shortNames:
    - pj